name: beast exe

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up go
      uses: actions/setup-python@v5
      with:
        go-version: '2.16'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        # আপনার প্রজেক্টে অতিরিক্ত কোনো লাইব্রেরি লাগলে এখানে ইনস্টল করতে পারেন যেমন: pip install requests

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile main.py 
        # খেয়াল রাখবেন: 'main.py' এর জায়গায় আপনার মূল পাইথন ফাইলের নাম হবে

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable
        path: dist/*.exe
